---
abstract: 'Alien package for libusb-1.0'
author:
  - 'Henrik Brix Andersen <brix@cpan.org>'
build_requires: {}
configure_requires:
  Alien::Base: 0.003
  Archive::Tar: 0
  Carp: 0
  Config: 0
  Env: 0
  Module::Build: 0.4004
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-LibUSBx
provides:
  Alien::LibUSBx:
    file: lib/Alien/LibUSBx.pm
    version: 0.10
requires:
  Alien::Base: 0.003
  File::ShareDir: 1.00
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
x_test_requires:
  Config: 0
  Test::More: 0
